name: Deploy

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true # Checkout private submodules(themes or something else).

    - name: Install Dependencies
      run: yarn

    # Deploy hexo blog website.
    - name: Deploy
      uses: yrpang/github-actions-hexo@master
        with:
          deploykey: ${{secrets.DEPLOY_KEY}}
          username: 'hiro0218'
          email: 'hiro0218@gmail.com'
