name: Deploy

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: A job to deploy blog.
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Update Submodules
      run: git submodule update --remote

    - name: Install Dependencies
      run: yarn

    - name: Prepare Deploy
      run: |
        yarn clean
        yarn build

    # Deploy hexo blog website.
    - name: Deploy
      uses: yrpang/github-actions-hexo@v1.3
      with:
        deploykey: ${{secrets.DEPLOY_KEY}}
        username: 'hiro0218'
        email: 'hiro0218@gmail.com'
